"""Change train losss column type

Revision ID: ddccc729fe05
Revises: 7e1a67f8a33e
Create Date: 2025-02-02 21:24:08.152068

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddccc729fe05"
down_revision: Union[str, None] = "7e1a67f8a33e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "epoch",
        "train_loss",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.Float()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "epoch",
        "train_loss",
        existing_type=sa.ARRAY(sa.Float()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
