"""Add indexes

Revision ID: e82429d99a75
Revises: 04ed66d2419b
Create Date: 2025-02-15 11:10:59.651637

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e82429d99a75"
down_revision: Union[str, None] = "04ed66d2419b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_agent_lhs_parent_id"), "agent", ["lhs_parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_rhs_parent_id"), "agent", ["rhs_parent_id"], unique=False
    )
    op.create_index(op.f("ix_avatar_agent_id"), "avatar", ["agent_id"], unique=False)
    op.create_index(op.f("ix_avatar_period_id"), "avatar", ["period_id"], unique=False)
    op.create_index(op.f("ix_avatar_zone_id"), "avatar", ["zone_id"], unique=False)
    op.create_index(op.f("ix_epoch_avatar_id"), "epoch", ["avatar_id"], unique=False)
    op.create_index(
        op.f("ix_mutation_agent_id"), "mutation", ["agent_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mutation_agent_id"), table_name="mutation")
    op.drop_index(op.f("ix_epoch_avatar_id"), table_name="epoch")
    op.drop_index(op.f("ix_avatar_zone_id"), table_name="avatar")
    op.drop_index(op.f("ix_avatar_period_id"), table_name="avatar")
    op.drop_index(op.f("ix_avatar_agent_id"), table_name="avatar")
    op.drop_index(op.f("ix_agent_rhs_parent_id"), table_name="agent")
    op.drop_index(op.f("ix_agent_lhs_parent_id"), table_name="agent")
    # ### end Alembic commands ###
